### ISSUE TITLE
db

### ISSUE THREAD

**Issue by asmolik** [s7impi/HelloWorld#2]
Tabela users - musi mieć pola username i password.
Tabela groups - musi mieć pola groupname i username.
Nazwy mogą się różnić od tych, ale User w aplikacji ma z tą bazą danych współpracować.
Na poniedziałek wystarczy tylko to (możliwość zapisania użytkownika).

Pewnie trzeba coś ustawić w persistence.xml i w glassfishu na wirtualnej maszynie.

**Comment by s7impi** [comment]
Baza poprawiona.
Nazwy tabel zostały zmienione na liczbe mnogą, ze względu na to, że pojawiają się u nas encje **orders**, a _ORDER_ jest słowem kluczowym w SQL'u.

**users** pola:
_id;_
_name;_
_password;_

**groups** pola:
_id;_
_name;_
_user_name;_

Nie powiązałem jeszcze _username'ów_ kluczem obcym, bo uważam, że w tym przypadku tabela **groups** powinna być nadrzędna. Dodam to, w momencie jak mi powiecie, że Wam również pasuje to koncepcyjnie.
![db](https://cloud.githubusercontent.com/assets/5671061/7550540/265ae04c-f666-11e4-884b-3e16209f2c62.png)
